/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    AccessTokens: () => import('#controllers/auth/access-tokens-controller'),
    EmailVerification: () => import('#controllers/auth/email-verification-controller'),
    NewAccount: () => import('#controllers/auth/new-account-controller'),
  },
  user: {
    User: () => import('#controllers/user/user-controller'),
  },
}
