/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    AccessTokens: () => import('#controllers/auth/access-tokens-controller'),
    NewAccount: () => import('#controllers/auth/new-account-controller'),
  },
  user: {
    Profile: () => import('#controllers/user/profile-controller'),
  },
}
